[project]
name = "simplegrad"
version = "0.1.0"
description = "A simple and lightweight autograd implementation"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.2",
    "torch>=2.5.1",
]
